name: Release and Publish Python Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
    - name: Install git-cliff
      uses: taiki-e/install-action@git-cliff
    - name: Generate changelog
      run: git-cliff -l > CHANGELOG.md
    - name: Build package
      run: |
        python3 -m build --sdist --wheel --outdir dist/ .
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        body_path: ./CHANGELOG.md
